version: '3.8'
services:
  db:
    image: mysql:8.2.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: ./backend  # backendフォルダがビルドコンテキスト
    command: bash -c "rm -f tmp/pids/server.pid && bundle check || bundle install && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api  # backendフォルダをコンテナの/apiディレクトリにマウント
    ports:
      - '3031:3000'  # ホストのポート3001をコンテナのポート3000にマッピング
    stdin_open: true
    tty: true
    depends_on:
      - db

  front:
    build: ./frontend/
    volumes:
      - ./frontend/app:/front
    ports:
      - 3030:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  mysql_data: